#!/bin/bash

#Define the threshold
THRESHOLD=1.00

# Get the current CPU load
LOAD=$(uptime | awk -F 'load average:' '{ print $2 }' | cut -d, -f1 | sed 's/ //g')

if (( $(echo "$LOAD > $THRESHOLD" | bc -l) )); then
	echo "Warning: CPU load is above $THRESHOLD."

else
	echo "CPU load is below $THRESHOLD."
fi
